In [1]:
import numpy as np
import math
from numpy import ndarray

In [ ]:
def get_primes_in_range(n: int):
    if (n > 6000):
        raise ValueError("The value is > 6000")
    if (n < 1):
        raise ValueError("The value is < 1")
    
    primes = [2]
    for i in range(3, n, 2):
        if all(i % j != 0 for j in range(3, int(math.sqrt(i)) + 1, 2)):
            primes.append(i)

    return primes

In [ ]:
def integer_primes(n: int):
    if (n > 6000):
        raise ValueError("The value is > 6000")
    if (n < 1):
        raise ValueError("The value is < 1")

    primes = []
    bound = math.ceil(math.sqrt(n))
    temp_n = n
    for a in range(2, bound + 1):
        for i in get_primes_in_range(n):
            if (temp_n % i == 0):
                temp_n = temp_n // i
                primes.append(i)
                
    if (temp_n != 1):
        primes.append(temp_n)

    return np.array(primes)

In [ ]:
integer_primes(6)

array([2, 3])

In [820]:
def print_as_block_matrix(matrix: ndarray) -> None:
    iSplit = np.array(matrix.shape[0::2])
    jSplit = np.array(matrix.shape[1::2])

    matrix_2d = matrix.reshape((iSplit.prod(), jSplit.prod()))

    string = ""

    def str_len(string):
        return len(str(string))
    str_len_func = np.vectorize(str_len)

    strings_len = str_len_func(matrix_2d)
    max_columns_len = np.max(strings_len, axis = 0)

    if (len(iSplit) > 1) or (len(jSplit) > 1):
        placeholder_len = 1 + 3 * len(jSplit) + np.sum(max_columns_len) + 2 * len(max_columns_len)
        placeholder = '|' + " "*placeholder_len + '|\n'

        string += placeholder

        for i in range(matrix_2d.shape[0]):
            string += "| |"

            for j in range(matrix_2d.shape[1]):
                string += f" {matrix_2d[i, j]} " + " " * (max_columns_len[j] - strings_len[i, j])

                if (j % jSplit[-1]) == 1:
                    string += "| |"

            string += "\n"

            if (i % iSplit[-1]) == 1:
                string += placeholder
    else:
        for i in range(matrix_2d.shape[0]):
            string += "| "

            for j in range(matrix_2d.shape[1]):
                string += f" {matrix_2d[i, j]} " + " " * (max_columns_len[j] - strings_len[i, j])

            string += " |\n"

    print(string)

In [821]:
a = np.array([[11, 1, 2, 2, 533, 6], [1, 1, 2, 2, 5, 6], [3, 3, 4, 4, 5, 6], [3, 3, 4, 4, 5, 6]])
b = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 5]])
print_as_block_matrix(a)
print_as_block_matrix(b)

|  11  1  2  2  533  6  |
|  1   1  2  2  5    6  |
|  3   3  4  4  5    6  |
|  3   3  4  4  5    6  |

|  2  2  2  2  |
|  2  2  2  2  |
|  2  2  2  2  |
|  2  2  2  2  |
|  2  2  2  2  |
|  2  2  2  5  |



In [824]:
print_as_block_matrix(a * 10)

|  110  10  20  20  5330  60  |
|  10   10  20  20  50    60  |
|  30   30  40  40  50    60  |
|  30   30  40  40  50    60  |



In [825]:
print_as_block_matrix(np.matmul(a, b))

|  1110  1110  1110  1128  |
|  34    34    34    52    |
|  50    50    50    68    |
|  50    50    50    68    |



In [ ]:
def kronecker_product(a: ndarray, b: ndarray):
    shape = a.shape + b.shape
    c = np.empty(shape, dtype=a.dtype)

    for i in np.ndindex(c.shape):
        c[i] = a[i[:len(a.shape)]] * b[i[len(a.shape):]]

    return c

In [ ]:
c1 = np.array([[1, 2], [3, 4], [3, 4]])
c2 = np.array([[1, 2], [1, 2]])

In [ ]:
c = kronecker_product(c1, c2)
print(c)

[[[[1 2]
   [1 2]]

  [[2 4]
   [2 4]]]


 [[[3 6]
   [3 6]]

  [[4 8]
   [4 8]]]


 [[[3 6]
   [3 6]]

  [[4 8]
   [4 8]]]]


In [826]:
print_as_block_matrix(c)

|                   |
| | 1  2 | | 1  2 | |
| | 2  4 | | 2  4 | |
|                   |
| | 3  6 | | 3  6 | |
| | 4  8 | | 4  8 | |
|                   |
| | 3  6 | | 3  6 | |
| | 4  8 | | 4  8 | |
|                   |

